/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.pol.user_service.schema.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ForgotPasswordEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6851385965809607922L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ForgotPasswordEvent\",\"namespace\":\"com.pol.user_service.schema.avro\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"otp\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ForgotPasswordEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ForgotPasswordEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ForgotPasswordEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ForgotPasswordEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ForgotPasswordEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ForgotPasswordEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ForgotPasswordEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ForgotPasswordEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ForgotPasswordEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence name;
  private java.lang.CharSequence email;
  private java.lang.CharSequence otp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ForgotPasswordEvent() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param email The new value for email
   * @param otp The new value for otp
   */
  public ForgotPasswordEvent(java.lang.CharSequence name, java.lang.CharSequence email, java.lang.CharSequence otp) {
    this.name = name;
    this.email = email;
    this.otp = otp;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return email;
    case 2: return otp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: email = (java.lang.CharSequence)value$; break;
    case 2: otp = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }


  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'otp' field.
   * @return The value of the 'otp' field.
   */
  public java.lang.CharSequence getOtp() {
    return otp;
  }


  /**
   * Sets the value of the 'otp' field.
   * @param value the value to set.
   */
  public void setOtp(java.lang.CharSequence value) {
    this.otp = value;
  }

  /**
   * Creates a new ForgotPasswordEvent RecordBuilder.
   * @return A new ForgotPasswordEvent RecordBuilder
   */
  public static com.pol.user_service.schema.avro.ForgotPasswordEvent.Builder newBuilder() {
    return new com.pol.user_service.schema.avro.ForgotPasswordEvent.Builder();
  }

  /**
   * Creates a new ForgotPasswordEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ForgotPasswordEvent RecordBuilder
   */
  public static com.pol.user_service.schema.avro.ForgotPasswordEvent.Builder newBuilder(com.pol.user_service.schema.avro.ForgotPasswordEvent.Builder other) {
    if (other == null) {
      return new com.pol.user_service.schema.avro.ForgotPasswordEvent.Builder();
    } else {
      return new com.pol.user_service.schema.avro.ForgotPasswordEvent.Builder(other);
    }
  }

  /**
   * Creates a new ForgotPasswordEvent RecordBuilder by copying an existing ForgotPasswordEvent instance.
   * @param other The existing instance to copy.
   * @return A new ForgotPasswordEvent RecordBuilder
   */
  public static com.pol.user_service.schema.avro.ForgotPasswordEvent.Builder newBuilder(com.pol.user_service.schema.avro.ForgotPasswordEvent other) {
    if (other == null) {
      return new com.pol.user_service.schema.avro.ForgotPasswordEvent.Builder();
    } else {
      return new com.pol.user_service.schema.avro.ForgotPasswordEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for ForgotPasswordEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ForgotPasswordEvent>
    implements org.apache.avro.data.RecordBuilder<ForgotPasswordEvent> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence email;
    private java.lang.CharSequence otp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.pol.user_service.schema.avro.ForgotPasswordEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.email)) {
        this.email = data().deepCopy(fields()[1].schema(), other.email);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.otp)) {
        this.otp = data().deepCopy(fields()[2].schema(), other.otp);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ForgotPasswordEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.pol.user_service.schema.avro.ForgotPasswordEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.email)) {
        this.email = data().deepCopy(fields()[1].schema(), other.email);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.otp)) {
        this.otp = data().deepCopy(fields()[2].schema(), other.otp);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.pol.user_service.schema.avro.ForgotPasswordEvent.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.pol.user_service.schema.avro.ForgotPasswordEvent.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmail() {
      return email;
    }


    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public com.pol.user_service.schema.avro.ForgotPasswordEvent.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.email = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public com.pol.user_service.schema.avro.ForgotPasswordEvent.Builder clearEmail() {
      email = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'otp' field.
      * @return The value.
      */
    public java.lang.CharSequence getOtp() {
      return otp;
    }


    /**
      * Sets the value of the 'otp' field.
      * @param value The value of 'otp'.
      * @return This builder.
      */
    public com.pol.user_service.schema.avro.ForgotPasswordEvent.Builder setOtp(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.otp = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'otp' field has been set.
      * @return True if the 'otp' field has been set, false otherwise.
      */
    public boolean hasOtp() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'otp' field.
      * @return This builder.
      */
    public com.pol.user_service.schema.avro.ForgotPasswordEvent.Builder clearOtp() {
      otp = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ForgotPasswordEvent build() {
      try {
        ForgotPasswordEvent record = new ForgotPasswordEvent();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.email = fieldSetFlags()[1] ? this.email : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.otp = fieldSetFlags()[2] ? this.otp : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ForgotPasswordEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ForgotPasswordEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ForgotPasswordEvent>
    READER$ = (org.apache.avro.io.DatumReader<ForgotPasswordEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.name);

    out.writeString(this.email);

    out.writeString(this.otp);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);

      this.otp = in.readString(this.otp instanceof Utf8 ? (Utf8)this.otp : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 1:
          this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);
          break;

        case 2:
          this.otp = in.readString(this.otp instanceof Utf8 ? (Utf8)this.otp : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}