server:
  port: 8084
  servlet:
    context-path: /payment-service

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edu_consult
    username: root
    password: Sireesha@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 5000
      minimum-idle: 3
      idle-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

razorpay:
  key_id: rzp_test_bRtKIk0SYwRB4K
  key_secret: qFgoCVBsB4Qw3FOQxUmsYNtK

